# Mapeia nomes conhecidos de DEX (como retornados pela DexScreener) para slugs válidos da DefiLlama
DEX_TO_DEFILLAMA_SLUG = {
    "uniswap": "uniswap",
    "pancakeswap": "pancakeswap",
    "sushiswap": "sushiswap",
    "curve": "curve",
    "velodrome": "velodrome-finance",
    "camelot": "camelot",
    "maverick": "maverick-protocol",
    "thena": "thena",
    "equalizer": "equalizer-exchange",
    "spookyswap": "spookyswap",
    "solidly": "solidlydex",
    "baseswap": "baseswap",
    "aerodrome": "aerodrome-finance",
    "orca": "orca",
    "raydium": "raydium",
    "jupiter": "jupiter-aggregator",
    "klex": "klex-finance",
    "beethovenx": "beethoven-x",
    "quickswap": "quickswap",
    "balancer": "balancer",
    "traderjoe": "trader-joe",
    "chronos": "chronos-finance"
}
